remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

title: "Recipes and Ratings Analysis"
description: "Cooking Up Insights: Analyzing Recipes and Ratings Data"

# Sidebar navigation
nav:
  - title: "Introduction"
    url: /
  - title: "Data Cleaning and Exploratory Data Analysis"
    url: /#data-cleaning-and-exploratory-data-analysis
  - title: "Framing a Prediction Problem"
    url: /#framing-a-prediction-problem
  - title: "Baseline Model"
    url: /#baseline-model
  - title: "Final Model"
    url: /#final-model
